### ISSUE TITLE
 evolution data-server: cannot install due to unmet dependency 'webkitgtk' 

### ISSUE THREAD

**Issue by worldofpeace** [softwareperonista/gnome-devel-pkgbuild#2]
### Installing evolution-data-server fails do to unmet dependency 'webkitgtk'.

In the [PKGBULID](https://github.com/softwareperonista/gnome-devel-pkgbuild/blob/master/evolution-data-server/PKGBUILD) there is a depends for 'webkitgtk'.

The package 'webkitgtk' isn't provided from the [Gnome-Devel Repo](https://softwareperonista.com.ar/repo/archlinux/gnome-devel/x86_64/) or the Arch repos.

Should this depends be webkit2gtk?

**Comment by IsoaSFlus** [comment]
I got this error too

**Comment by worldofpeace** [comment]
This has been fixed f03ce3264f6487d2b46607ecf9e288d804e4f372
